// 1 rows == 1 cols == 142px
const itemsList = [
  {
    img: './SAMPLE_PICTURES/blackwood.jpg',
    link: './SAMPLE_BANNERS/Blackwood_300-250/1.html',
    title: 'Blackwood Barbers',
    subtitle: 'Fine Haircuts & Shaves',
    width: 300,
    height: 250,
    cols: 2,
    rows: 2,
  },
  {
    img: './SAMPLE_PICTURES/Oxford_MBA_300-142.jpg',
    link: './SAMPLE_BANNERS/Oxford_MBA_300-600/1.html',
    title: 'Executive MBA',
    subtitle: 'London University World class Education',
    width: 300,
    height: 600,
    cols: 2,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/upwork_150.jpg',
    link: 'https://www.upwork.com/freelancers/~0102b4d3fa21effab2',
    title: 'Upwork',
    subtitle: '',
    width: 240,
    height: 400,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/nda_150.jpg',
    link: './SAMPLE_PICTURES/NDA_BIG.jpg',
    title: '',
    subtitle:
      "Really significant project is hidden here. Unfortunately I'm not allowed to uncover details of those great and impactful animated ads I produced within campaign for well know brand from USA Top 100",
    width: 300,
    height: 250,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/Kronos_Giveaway_142-142.jpg',
    link: './SAMPLE_BANNERS/Kronos_Giveaway_240-400/1.html',
    title: 'Giveaway',
    subtitle: 'New Dealer Center Grand\xA0Opening',
    width: 240,
    height: 400,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/years_150.jpg',
    link: '',
    title: '17 years',
    subtitle: '',
    width: 240,
    height: 400,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/nails.jpg',
    link: './SAMPLE_BANNERS/NailsAmore_300-600/1.html',
    title: 'Nails Amore',
    subtitle: 'New Salon Gift Sertificate',
    width: 300,
    height: 600,
    cols: 2,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/Kings_City_300-300.jpg',
    link: './SAMPLE_BANNERS/Kings_City_300-600/1.html',
    title: "King's City",
    subtitle: 'London Business College',
    width: 300,
    height: 600,
    cols: 2,
    rows: 2,
  },
  {
    img: './SAMPLE_PICTURES/Access_Bank_UK_300-142.jpg',
    link: './SAMPLE_BANNERS/Access_Bank_UK_300-600/1.html',
    title: 'United Kingdom Bank',
    subtitle: 'Access more opportunities',
    width: 300,
    height: 600,
    cols: 2,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/Astronaut_142-142.jpg',
    link: './SAMPLE_BANNERS/Astronaut_300-300/1.html',
    title: 'Astronaut',
    subtitle: 'Marketing Agency site animation',
    width: 300,
    height: 300,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/Squared_Neon_142-142.jpg',
    link: './SAMPLE_BANNERS/Squared_Neon_300-600/1.html',
    title: 'Neon Lights',
    subtitle: 'Google Ads Targeting Services',
    width: 300,
    height: 600,
    cols: 1,
    rows: 1,
  },

  {
    img: './SAMPLE_PICTURES/wagners.jpg',
    link: './SAMPLE_BANNERS/Wagners_300-600/1.html',
    title: 'Wagners',
    subtitle: 'Personal Injury Lawers',
    width: 300,
    height: 600,
    cols: 2,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/quad.png',
    link: './SAMPLE_BANNERS/Quad_300-600/1.html',
    title: 'QUAD',
    subtitle: 'Premium Students Apartments',
    width: 300,
    height: 600,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/magnit_tires.jpg',
    link: './SAMPLE_BANNERS/Magnit_bear_tires_240-400/1.html',
    title: 'Magnit',
    subtitle: 'Used tires from Japan',
    width: 240,
    height: 400,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/Kronos_Headache_300-300.jpg',
    link: './SAMPLE_BANNERS/Kronos_Headache_240-400/1.html',
    title: 'Headache',
    subtitle: 'When searching auto parts is headache',
    width: 240,
    height: 400,
    cols: 2,
    rows: 2,
  },
  {
    img: './SAMPLE_PICTURES/lavanda.png',
    link: './SAMPLE_BANNERS/Lavanda_336-280/1.html',
    title: 'Lavanda',
    subtitle: 'Airbnb management',
    width: 336,
    height: 280,
    cols: 2,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/Kings_IOPPN_300-142.jpg',
    link: './SAMPLE_BANNERS/Kings_IOPPN_300-600/1.html',
    title: "King's IOPPN",
    subtitle: 'London Institute of Psychiatry, Psychology & Neuroscience',
    width: 300,
    height: 600,
    cols: 2,
    rows: 1,
  },

  {
    img: './SAMPLE_PICTURES/Paper_Planes_142-142.jpg',
    link: './SAMPLE_BANNERS/Paper_Planes_300-250/1.html',
    title: 'Paper Planes',
    subtitle: 'Marketing Agency Self Ad',
    width: 300,
    height: 250,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/kronos_dismantle.png',
    link: './SAMPLE_BANNERS/Kronos_Dismantle_240-400/1.html',
    title: 'Dismantling',
    subtitle: 'Kronos Cars dismantling',
    width: 240,
    height: 400,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/Tours_Day_Tours_142-142.jpg',
    link: './SAMPLE_BANNERS/Tours_Day_Tours_300-250/1.html',
    title: 'Day Tours',
    subtitle: 'Australia Sea Day Tours',
    width: 300,
    height: 250,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/Summer_Land_Camel_Milk_142-142.jpg',
    link: './SAMPLE_BANNERS/Summer_Land_Camel_Milk_300-250/1.html',
    title: 'Summer Land',
    subtitle: 'Camel Milk Farm',
    width: 300,
    height: 250,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/MYO_300-300.jpg',
    link: './SAMPLE_BANNERS/MYO_300-250/1.html',
    title: 'MYO',
    subtitle: 'Office space special services',
    width: 300,
    height: 250,
    cols: 2,
    rows: 2,
  },
  {
    img: './SAMPLE_PICTURES/LG_Washing_Machine_300-142.jpg',
    link: './SAMPLE_BANNERS/LG_Washing_Machine_300-600/1.html',
    title: 'LG Washing Machine',
    subtitle: 'Store SALE Ad',
    width: 300,
    height: 600,
    cols: 2,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/autoparts.png',
    link: './SAMPLE_BANNERS/Concept_auto_parts_240-400/1.html',
    title: 'Auto Parts',
    subtitle: 'Japan Auto parts delivery',
    width: 240,
    height: 400,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/nda_150.jpg',
    link: './SAMPLE_PICTURES/NDA_BIG.jpg',
    title: '',
    subtitle:
      "Really significant project is hidden here. Unfortunately I'm not allowed to uncover details of those great and impactful animated ads I produced within campaign for well know brand from USA Top100",
    width: 300,
    height: 250,
    cols: 1,
    rows: 1,
  },

  {
    img: './SAMPLE_PICTURES/Dnovo_We_Offer_142-142.jpg',
    link: './SAMPLE_BANNERS/Dnovo_We_Offer_336-280/1.html',
    title: 'We Offer',
    subtitle: 'Marketing Agency Self Ad',
    width: 336,
    height: 280,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/Cemoh_142-142.jpg',
    link: './SAMPLE_BANNERS/Cemoh_300-250/1.html',
    title: 'CEMOH',
    subtitle: 'Marketing Agency Self Ad',
    width: 300,
    height: 250,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/Violife_Bagel_300-142.jpg',
    link: './SAMPLE_BANNERS/Violife_Bagel_300-250/1.html',
    title: '100% Vegan Cheese',
    subtitle: 'Completely Dairy Free',
    width: 300,
    height: 250,
    cols: 2,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/Kursi_Book_300-300.jpg',
    link: './SAMPLE_BANNERS/Kursi_Book_300-600/1.html',
    title: 'Kursi Catalogue',
    subtitle: 'Store New Catalogue Ad',
    width: 300,
    height: 600,
    cols: 2,
    rows: 2,
  },
  {
    img: './SAMPLE_PICTURES/Glenlyon_142-142.jpg',
    link: './SAMPLE_BANNERS/Glenlyon_300-250/1.html',
    title: 'Glenlyon',
    subtitle: 'Australia Real Estate',
    width: 300,
    height: 250,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/Tours_Kimberly_Tours_142-142.jpg',
    link: './SAMPLE_BANNERS/Tours_Kimberly_Tours_300-250/1.html',
    title: 'Kimberly',
    subtitle: 'Australia Safari Tours',
    width: 300,
    height: 250,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/Pooky_300-142.jpg',
    link: './SAMPLE_BANNERS/Pooky_300-250/1.html',
    title: 'Pooky',
    subtitle: 'Beautiful decorative lighting',
    width: 300,
    height: 250,
    cols: 2,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/Oxford_DipSI_300-142.jpg',
    link: './SAMPLE_BANNERS/Oxford_DipSI_300-600/1.html',
    title: 'Postgradute Qualification',
    subtitle: 'Diploma in Strategy and Innovation',
    width: 300,
    height: 600,
    cols: 2,
    rows: 1,
  },

  {
    img: './SAMPLE_PICTURES/Vpoloborota_142-142.jpg',
    link: './SAMPLE_BANNERS/Vpoloborota_240-400/1.html',
    title: 'Vpoloborota',
    subtitle: 'Batteries and auto parts',
    width: 240,
    height: 400,
    cols: 1,
    rows: 1,
  },

  {
    img: './SAMPLE_PICTURES/Squared_Searchlight_142-142.jpg',
    link: './SAMPLE_BANNERS/Squared_Searchlight_300-250/1.html',
    title: 'Squared',
    subtitle: 'Google Ads Targeting Services',
    width: 300,
    height: 250,
    cols: 1,
    rows: 1,
  },

  {
    img: './SAMPLE_PICTURES/Maxima_300-300.jpg',
    link: './SAMPLE_BANNERS/Maxima_300-600/1.html',
    title: 'Maxima Lottery',
    subtitle: 'Store Lottery Ad',
    width: 300,
    height: 600,
    cols: 2,
    rows: 2,
  },

  {
    img: './SAMPLE_PICTURES/Kings_Start_300-142.jpg',
    link: './SAMPLE_BANNERS/Kings_Start_300-600/1.html',
    title: "King's Start",
    subtitle: 'London University Open Day invitation',
    width: 300,
    height: 600,
    cols: 2,
    rows: 1,
  },

  {
    img: './SAMPLE_PICTURES/nda_150.jpg',
    link: './SAMPLE_PICTURES/NDA_BIG.jpg',
    title: '',
    subtitle:
      "Really significant project is hidden here. Unfortunately I'm not allowed to uncover details of those great and impactful animated ads I produced within campaign for well know brand from USA Top100",
    width: 300,
    height: 250,
    cols: 1,
    rows: 1,
  },
  {
    img: './SAMPLE_PICTURES/marussia.png',
    link: './SAMPLE_BANNERS/Marussya_240-400/1.html',
    title: 'Marussya',
    subtitle: 'Food delivery',
    width: 240,
    height: 400,
    cols: 1,
    rows: 1,
  },
];

export default itemsList;
